title: Souvenirs of an Electric co.
owner: Florent Dufour
email: blog@dufour.xyz
keywords: [florent, dufour, blog, xyz, AI, Munich, blockchain, health, research, privacy]
description: Florent Dufour's blog
parent: "https://dufour.xyz"
url: "https://blog.dufour.xyz"
language: en
encoding: utf-8
timezone: Europe/Paris
permalink: /:year/:title
excerpt_separator: <!--more-->

theme-color: "#fdf52b"
theme-color-dark: "#333"

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - rouge

exclude:
  - vendor/bundle
  - _posts/hidden

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
