title: Souvenirs of an Electric Co.
owner: Florent Dufour
email: blog@dufour.xyz
keywords: [florent, dufour, blog, xyz, AI, Munich, blockchain, health, research, privacy]
description: Florent Dufour's blog
parent: "https://dufour.xyz"
theme-color: "#fdf52b"
theme-color-dark: "#333"

url: "https://blog.dufour.xyz"
language: en
encoding: utf-8
timezone: Europe/Paris
markdown: kramdown
permalink: /:year/:title

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - _posts/hidden

excerpt_separator: <!--more-->

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
