title: Souvenirs of an Electric Co.
owner: Florent Dufour
name: Florent Dufour
email: blog@dufour.xyz
description: Florent Dufour's blog
theme-color: "#fdf52b"

url: "https://blog.dufour.xyz"
language: en
encoding: utf-8
timezone: Europe/Paris
markdown: kramdown
permalink: /:year/:title

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - _posts/hidden

excerpt_separator: <!--more-->
paginate: 10
paginate_path: ":num"

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
